version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - chromadb
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - .env.example
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
volumes:
  chromadb_data:
    driver: local
  ollama_data:
    driver: local
