version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - chromadb
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - .env.example
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
volumes:
  chromadb_data:
    driver: local
